<!-- BEGIN: MAIN -->

<!-- BEGIN: ROW -->
{SEP} {EXP_ROW_SHORTTITLE}; {EXP_ROW_TOVAR_TITLE}; {EXP_ROW_TOVAR_SHORT_DESC}; {EXP_ROW_DESC}; {EXP_ROW_CENA}; {EXP_ROW_SHOP_PRICE}; {EXP_ROW_NALICHIE};  {EXP_ROW_SHOP_INSTOCK}; {EXP_ROW_SALE}; {EXP_ROW_SALE_PRICE}; {EXP_ROW_SALE_DESCRIPTION}; {EXP_ROW_BRAND_NAME}; {EXP_ROW_BRAND_PICTURE_URL}; {EXP_ROW_TOVAR_PICTURE}; {EXP_ROW_TOVAR_PICTURE_ALT}; {EXP_ROW_TOVAR_SMALL_PICTURE}; {EXP_ROW_VKREDIT}; {EXP_ROW_VKREDIT_CENA}; {EXP_ROW_VKREDIT_DESCR};
<!-- END: ROW -->

<!-- END: MAIN -->